name: Run JS E2E Tests on iOS & Android

on:
  workflow_call:
    inputs:
      android-wallet-name:
        required: true
        type: string
      ios-wallet-name:
        required: true
        type: string
      webdapp-url:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      android-wallet-name:
        required: true
        description: 'The BrowserStack app name for the MetaMask Android wallet app (QA Build)'
        type: string
      ios-wallet-name:
        required: true
        description: 'The BrowserStack app name for the MetaMask iOS wallet app (QA Build)'
        type: string
      webdapp-url:
        required: true
        description: 'From the CI deploy'
        type: string

jobs:
  e2e-tests-js-sdk:
    runs-on: ubuntu-latest
    env:
      SRP: ${{ secrets.SRP }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_API_USERNAME: ${{ secrets.BROWSERSTACK_API_USERNAME }}
      BROWSERSTACK_API_PASSWORD: ${{ secrets.BROWSERSTACK_API_PASSWORD }}

    steps:
      - name: 'BrowserStack Local Tunnel Setup'
        uses: browserstack/github-actions/setup-local@091a1cfc5a170370a5a30f906be08adfb123dd9f
        with:
         local-testing: start
         local-identifier: random

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'
          cache: yarn

      - name: Install Dependencies
        run: yarn install && cd e2e && yarn install && cd ..

      - name: Build SDK Repo
        run: yarn build

      - name: Create .ios.env & .android.env
        working-directory: ./e2e
        run: |
          browserstack_api_url="https://api-cloud.browserstack.com/app-automate/recent_apps/"
          response=$(curl -s -u "$BROWSERSTACK_API_USERNAME:$BROWSERSTACK_API_PASSWORD" "$browserstack_api_url")
          ios_wallet_app_name="${{ inputs.ios-wallet-name }}"
          android_wallet_app_name="${{ inputs.android-wallet-name }}"

          # Gets the app_url and custom_id for the wallet app and the react native test app to use in the .ios.env and .android.env file
          ios_wallet_app_url=$(echo "$response" | jq -r --arg ios_wallet_app_name "$ios_wallet_app_name" '.[] | select(.app_name == $ios_wallet_app_name) | .app_url')
          ios_wallet_app_bundle_id=$(echo "$response" | jq -r --arg ios_wallet_app_name "$ios_wallet_app_name" '.[] | select(.app_name == $ios_wallet_app_name) | .custom_id')
          android_wallet_app_url=$(echo "$response" | jq -r --arg android_wallet_app_name "$android_wallet_app_name" '.[] | select(.app_name == $android_wallet_app_name) | .app_url')
          android_wallet_app_bundle_id=$(echo "$response" | jq -r --arg android_wallet_app_name "$android_wallet_app_name" '.[] | select(.app_name == $android_wallet_app_name) | .custom_id')


          # Writes to the .ios.env file
          {
            echo "APP_PATH=$ios_wallet_app_url"
            echo "BUNDLE_ID=$ios_wallet_app_bundle_id"
          } >> .ios.env

          # Writes to the .android.env file
          {
            echo "APP_PATH=$android_wallet_app_url"
            echo "BUNDLE_ID=$android_wallet_app_bundle_id"
          } >> .android.env

      - name: Set Dapps Environment Variables
        working-directory: ./e2e
        run: |
          {
            echo "DEVNEXT_URL=http://localhost:3333"
            echo "WEBDAPP_URL=${{ inputs.webdapp-url }}"
          } >> .dapps.env

      - name: Start the Devnext dapp
        working-directory: ./packages/devnext
        run: |
          yarn dev &
          sleep 20

      - name: Run JS-SDK iOS E2E tests
        working-directory: ./e2e
        run: yarn test:ios:jssdk:e2e:browserstack

      - name: Run JS-SDK Android E2E tests
        working-directory: ./e2e
        run: yarn test:android:jssdk:e2e:browserstack

      - name: Stop the Devnext dapp
        run: |
          kill $(lsof -t -i:3333)

      - name: 'BrowserStackLocal Stop'
        uses: browserstack/github-actions/setup-local@091a1cfc5a170370a5a30f906be08adfb123dd9f
        with:
          local-testing: stop


